[package]
name = "paste"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.12.8", features = ["default-tls", "cookies", "socks"] }
tokio = { version = "1.40.0", features = ["rt", "rt-multi-thread", "macros"] }
dom_query = "0.5.0"
regex = "1.11.0"